services:
  v2ray-nodpi:
    build:
      context: ../../
      dockerfile: ./deploy/docker/Dockerfile
    ports:
      - "443:443"
    volumes:
      - type: bind
        read_only: true
        source: ./config.json
        target: /config.json
    restart: unless-stopped
