version: '3.8'
services:
  v2ray-server:
    build:
      context: ../../
      dockerfile: ./deploy/docker/Dockerfile
    ports:
      - "25565:25565"
    volumes:
      - type: bind
        source: ./config.json
        target: /config.json