services:
  v2ray-server:
    build:
      context: ../../
      dockerfile: ./deploy/docker/Dockerfile
    ports:
      - "30000-30100:30000-30100"
    network_mode: "host"
    volumes:
      - type: bind
        source: ./config.json
        target: /config.json