services:
  v2ray-nodpi:
    build:
      context: ../../
      dockerfile: ./deploy/docker/Dockerfile
    ports:
      - "44300:443"
      - "30000:30000"
    volumes:
      - type: bind
        read_only: true
        source: ./config.json
        target: /config.json
    restart: unless-stopped
    privileged: true
    network_mode: host
